# Generated by Django 5.1.7 on 2025-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coattainment',
            name='attainment_percentage',
        ),
        migrations.AddField(
            model_name='coattainment',
            name='level_avg',
            field=models.FloatField(default=0),
        ),
    ]
