# Generated by Django 5.1.7 on 2025-08-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_merge_0002s'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtained', models.FloatField(default=0)),
                ('total_max', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
