# Generated by Django 5.1.7 on 2025-08-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0005_recreate_studentmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='COAggregateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_obtained_marks', models.FloatField(default=0)),
                ('total_max_marks', models.FloatField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.co')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
            ],
            options={
                'unique_together': {('course', 'co')},
            },
        ),
    ]
