# Generated by Django 5.1.7 on 2025-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0006_coaggregatescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='attainment_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1),
        ),
    ]
