# Generated by Django 5.1.7 on 2025-08-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0007_studentmark_attainment_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='POAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_score', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.course')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.po')),
            ],
            options={
                'unique_together': {('course', 'po')},
            },
        ),
    ]
